### PR TITLE
removing unneeded trim

### PR DESCRIPTION
**Pull request by pjaudiomv**

### CODE REVIEW

**Comment by leewillis77** [comment]
Is this actually breaking anything for you? If so, can you provide an example URL that doesn't work with the shipped code, but does with this change in place. 

From memory, the repository is guaranteed not to contain a trailing slash by the matching regexp so the trim is actually irrelevant (and therefore should be removed, not "fixed").

**Comment by pjaudiomv** [comment]
Your right, and I thought the same thing. It's just stale code. I will alter appropriately.

**Comment by pjaudiomv** [comment]
going to test this before resolving wip

**Comment by pjaudiomv** [comment]
resolving wip, tested this is fine.

**Comment by leewillis77** [comment]
Merged - thanks!

**Pull request merged**
